### Admin Login
POST https://lil-project-1.herokuapp.com/api/admin/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}


### Get all Demo Requests
GET https://lil-project-1.herokuapp.com/api/demorequests
Authorization: 


### Get One Demo Request
GET https://lil-project-1.herokuapp.com/api/demorequests/5f07020c1ec8572fa8585f2c
Authorization: 


### Get All Contact Us Details
GET https://lil-project-1.herokuapp.com/api/contactus
Authorization: 


### Get One Contact Us Detail
GET https://lil-project-1.herokuapp.com/api/contactus/5f0704b2acc11e363b01251f
Authorization: 


###
