### Admin Login
POST https://lil-project-1.herokuapp.com/api/admin/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}


### Get all Demo Requests
GET https://lil-project-1.herokuapp.com/api/demorequests
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjA4MDcyZTBjZDJhNzNhMWM0OTY5MTYiLCJpYXQiOjE1OTQzNjI1Nzl9.i-J2QxQlDalV2AKkkgTCIUiznIoQhCdLz8zddvzVhkE 


### Get One Demo Request
GET https://lil-project-1.herokuapp.com/api/demorequests/5f07020c1ec8572fa8585f2c
Authorization: 


### Get All Contact Us Details
GET https://lil-project-1.herokuapp.com/api/contactus
Authorization: 


### Get One Contact Us Detail
GET https://lil-project-1.herokuapp.com/api/contactus/5f0704b2acc11e363b01251f
Authorization: 


### Get All Testimonials
GET https://lil-project-1.herokuapp.com/api/testimonials


### Get All Deleted Testimonials
GET https://lil-project-1.herokuapp.com/api/testimonials?deleted=true
Authorization: 


### Get One Testimonial
GET https://lil-project-1.herokuapp.com/api/testimonials/5f0aa2e2c9da121df8368fc2


### Add Testimonial
POST https://lil-project-1.herokuapp.com/api/testimonials
Authorization: 
Content-Type: multipart/form-data

{
    "name": "Test Name",
    "email": "test@test.com",
    "comment": "test comment",
    "image": "jpg, jpeg or png less than 5 mb"
}


### Delete Testimonial
DELETE https://lil-project-1.herokuapp.com/api/testimonials/5f0aa2e2c9da121df8368fc2
Authorization: 


### Restore Testimonial
DELETE https://lil-project-1.herokuapp.com/api/testimonials/5f0aa2e2c9da121df8368fc2?delete=false
Authorization: 


###
